name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: json-lint
        uses: ocular-d/json-linter@0.0.2

      - name: markdown-lint
        uses: avto-dev/markdown-lint@v1.5.0
